In [1]:
import pandas as pd

In [2]:
Order_df=pd.read_json(r"c:\Users\sindh\OneDrive\Documents\Data science GUVI\Project 1 - Uber eats\orders.json")

In [3]:
Order_df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

In [4]:
Order_df.dtypes

order_id               str
restaurant_name        str
order_date             str
order_value        float64
discount_used          str
payment_method         str
dtype: object

In [5]:
Order_df['order_date']=pd.to_datetime(Order_df['order_date'])

In [6]:
Order_df['payment_method'].value_counts()

payment_method
Cash    8384
Card    8364
UPI     8252
Name: count, dtype: int64

In [7]:
Order_df['discount_used'].value_counts()

discount_used
No     12509
Yes    12491
Name: count, dtype: int64

In [8]:
Order_df['order_value'].value_counts()

order_value
553.52     4
1092.84    4
418.46     4
490.43     4
937.88     3
          ..
1254.91    1
760.39     1
707.99     1
724.29     1
905.00     1
Name: count, Length: 23212, dtype: int64

In [9]:
import sqlite3

In [10]:
conn = sqlite3.connect("uber_eats.db")

In [11]:
query = "SELECT name FROM sqlite_master WHERE type='table';"

pd.read_sql(query, conn)

            name
0       Order_id
1    restaurants
2  Order_details

In [12]:
Order_df.to_sql(
    name="Order_details",
    con=conn,
    if_exists="replace",
    index=False)

25000

In [13]:
Order_df

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI
...,...,...,...,...,...,...
24995,74d3cd31-c1e0-4331-aad7-e1f48b4698ae,Carnatic,2025-11-24,1254.91,No,UPI
24996,14db2f6b-f722-44a2-ae55-fe42511e4bb2,Reddy's Restaurant,2025-06-24,760.39,No,Card
24997,0fd85321-c1ce-4163-beca-c8ed2b472b8d,BTM Bawarchi Biryani,2025-12-04,707.99,Yes,Card
24998,6b96c699-2d63-4a3c-84f1-5d52ca4bf357,Nite Out,2025-09-21,724.29,Yes,Card
24999,af55e28b-27fc-49fc-bdb0-b297999dd152,Zee5 Loft,2025-08-07,905.00,No,UPI

In [14]:
query=" SELECT * FROM ORDER_DETAILS"

In [15]:
pd.read_sql(query,conn)

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06 00:00:00,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08 00:00:00,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22 00:00:00,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10 00:00:00,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22 00:00:00,1551.09,Yes,UPI
...,...,...,...,...,...,...
24995,74d3cd31-c1e0-4331-aad7-e1f48b4698ae,Carnatic,2025-11-24 00:00:00,1254.91,No,UPI
24996,14db2f6b-f722-44a2-ae55-fe42511e4bb2,Reddy's Restaurant,2025-06-24 00:00:00,760.39,No,Card
24997,0fd85321-c1ce-4163-beca-c8ed2b472b8d,BTM Bawarchi Biryani,2025-12-04 00:00:00,707.99,Yes,Card
24998,6b96c699-2d63-4a3c-84f1-5d52ca4bf357,Nite Out,2025-09-21 00:00:00,724.29,Yes,Card
24999,af55e28b-27fc-49fc-bdb0-b297999dd152,Zee5 Loft,2025-08-07 00:00:00,905.00,No,UPI

In [16]:
pd.read_sql("PRAGMA table_info(restaurants);", conn)

    cid                         name     type  notnull dflt_value  pk
0     0                         name     TEXT        0       None   0
1     1                 online_order     TEXT        0       None   0
2     2                   book_table     TEXT        0       None   0
3     3                         rate     REAL        0       None   0
4     4                        votes  INTEGER        0       None   0
5     5                        phone     TEXT        0       None   0
6     6                     location     TEXT        0       None   0
7     7                    rest_type     TEXT        0       None   0
8     8                   dish_liked     TEXT        0       None   0
9     9                     cuisines     TEXT        0       None   0
10   10  approx_cost(for two people)  INTEGER        0       None   0
11   11              listed_in(type)     TEXT        0       None   0
12   12              listed_in(city)     TEXT        0       None   0

In [17]:
pd.read_sql("PRAGMA table_info(Order_details);", conn)

   cid             name       type  notnull dflt_value  pk
0    0         order_id       TEXT        0       None   0
1    1  restaurant_name       TEXT        0       None   0
2    2       order_date  TIMESTAMP        0       None   0
3    3      order_value       REAL        0       None   0
4    4    discount_used       TEXT        0       None   0
5    5   payment_method       TEXT        0       None   0

In [18]:
query1 = """
SELECT LOCATION , round(AVG(RATE),2) as Avg_rating FROM restaurants
group by LOCATION
ORDER BY Avg_rating desc
LIMIT 10
"""

q1 = pd.read_sql(query1, conn)
q1

                location  Avg_rating
0           Lavelle Road        4.19
1  Koramangala 5th Block        4.15
2            Sankey Road        4.11
3         St. Marks Road        4.10
4  Koramangala 3rd Block        4.10
5        Cunningham Road        4.10
6  Koramangala 2nd Block        4.07
7         Sadashiv Nagar        4.06
8         Residency Road        4.05
9          Church Street        4.05

In [19]:
import plotly.express as px
import streamlit as st

In [20]:
pip install --upgrade nbformat

Requirement already satisfied: nbformat in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\sindh\AppData\Roaming\Python\Python312\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\sindh\AppData\Roaming\Python\Python312\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from jsonschema>=2.6->nbformat) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\sindh\AppData\Roaming\Python\Python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\Users\sindh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
import plotly.express as px

fig = px.bar(
    q1,
    x="Avg_rating",
    y="location",
    orientation="h",
    text="Avg_rating",
    title="Top 10 Locations by Average Rating",
    color_discrete_sequence=["#F5AFAF"]
)

fig.update_traces(textposition="outside")

fig.update_layout(
    height=500,
    width=800,
    margin=dict(l=200, r=20, t=50, b=50),
    xaxis=dict(range=[4.0, 4.2]),
    yaxis=dict(autorange="reversed"),
    yaxis_title="",
    xaxis_title="<b>Average Rating</b>"
)

fig.show()

In [22]:
query2 = """
SELECT location,
       COUNT(*) AS restaurant_count
FROM restaurants
GROUP BY location
ORDER BY restaurant_count DESC
limit 10;
"""

q2 = pd.read_sql(query2, conn)
q2

                location  restaurant_count
0  Koramangala 5th Block              1782
1                    BTM              1454
2            Indiranagar              1344
3                    HSR              1161
4              Jayanagar              1037
5               JP Nagar              1016
6             Whitefield               824
7  Koramangala 7th Block               723
8  Koramangala 6th Block               718
9           Marathahalli               680

In [23]:
fig2 = px.bar(
    q2,
    x="restaurant_count",
    y="location",
    orientation="h",
    text="restaurant_count",
    title="oversaturated location with restaurant",
    color_discrete_sequence=["#dec0f1"]
)
fig2.update_traces(textposition="outside")

fig2.update_layout(
    height=500,
    width=1000,
    margin=dict(l=200, r=30, t=50, b=150),
    
    xaxis=dict(range=[600,1900]),
    #yaxis=dict(range=[600,2000]),
    yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    yaxis_title="",
    xaxis_title="<b>restaurant_count</b>"
)

In [24]:
query3= """
SELECT online_order,round(AVG(RATE),2) as Avg_rating FROM restaurants
group by online_order
"""

q3= pd.read_sql(query3, conn)
q3

  online_order  Avg_rating
0           No        3.93
1          Yes        3.89

In [25]:
fig3 = px.bar(
    q3,
    x="online_order",
    y="Avg_rating",
    #orientation="h",
    text="Avg_rating",
    title="Online Ordering Vs Restaurant Rating",
    color_discrete_sequence=["#f8ff96"]
)

fig3.update_traces(textposition="outside")

fig3.update_layout(
    height=500,
    width=600,
    #template="plotly_white",
    margin=dict(l=50, r=30, t=50, b=30),
    
    #xaxis=dict(range=[600,1900]),
    yaxis=dict(range=[3.5,4]),
   # yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    yaxis_title="Rating",
    xaxis_title="<b>Online_order </b>"
)

In [26]:
query = """
SELECT *
FROM restaurants
LIMIT 10
"""

top10 = pd.read_sql(query, conn)
top10

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,"080 42297555, +91 9743772233",Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,"+91 8026612447, +91 9901210005",Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
5,Timepass Dinner,Yes,No,3.8,286,"+91 9980040002, +91 9980063005",Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,Buffet,Banashankari
6,Onesta,Yes,Yes,4.6,2556,"080 48653961, 080 48655715",Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,Cafes,Banashankari
7,Penthouse Cafe,Yes,No,4.0,324,"+91 8884135549, +91 9449449316",Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,Cafes,Banashankari
8,Smacznego,Yes,No,4.2,504,"+91 9945230807, +91 9743804471",Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,Cafes,Banashankari
9,CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1,402,"080 26724489, +91 7406048982",Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500,Cafes,Banashankari

In [27]:
q2.duplicated().sum()

np.int64(0)

In [28]:
query4 = """
SELECT book_table,avg(rate) as Avg_rating FROM restaurants
group by book_table

"""

q4 = pd.read_sql(query4, conn)
q4

  book_table  Avg_rating
0         No    3.813145
1        Yes    4.160130

In [29]:
fig4 = px.bar(
    q4,
    x="book_table",
    y="Avg_rating",
    #orientation="h",
    text="Avg_rating",
    title="Corelation between Table booking and Rating",
    color_discrete_sequence=["#faeca2"]
)

fig4.update_traces(textposition="outside")

fig4.update_layout(
    height=500,
    width=600,
    #template="plotly_white",
    margin=dict(l=50, r=30, t=50, b=30),
    
    #xaxis=dict(range=[600,1900]),
    yaxis=dict(range=[3.5,4.3]),
   # yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    yaxis_title="<b>Rating</b>",
    xaxis_title="<b>Table booking </b>"
)

In [30]:
query5 = """
SELECT
    CASE
    WHEN "approx_cost(for two people)" <= 400 THEN 'Low'
    WHEN "approx_cost(for two people)" <= 1000 THEN 'Mid'
    ELSE 'Premium'
   END as price_segment,

    ROUND(AVG(rate),2) AS avg_rating,
    COUNT(*) AS restaurant_count

FROM restaurants

GROUP BY price_segment
order by avg_rating desc
"""
q5= pd.read_sql(query5, conn)
q5

  price_segment  avg_rating  restaurant_count
0       Premium        4.18              4738
1           Mid        3.85             11629
2           Low        3.82              6784

In [31]:
fig5 = px.bar(
    q5,
    x="price_segment",
    y="avg_rating",
    #orientation="h",
    text="avg_rating",
    title="Segment performing well",
    color_discrete_sequence=["#003049"]
)

fig5.update_traces(textposition="outside")

fig5.update_layout(
    height=500,
    width=600,
    #template="plotly_white",
    margin=dict(l=50, r=30, t=50, b=30),
    
    #xaxis=dict(range=[600,1900]),
    #yaxis=dict(range=[3.5,4.3]),
   # yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    yaxis_title="<b>Average rating</b>",
    xaxis_title="<b>price segment </b>"
)

In [32]:
query6 = """
SELECT
    CASE
    WHEN "approx_cost(for two people)" <= 400 THEN 'Low'
    WHEN "approx_cost(for two people)" <= 1000 THEN 'Mid'
    ELSE 'Premium'
   END as price_segment,

    ROUND(AVG(rate),2) AS avg_rating,
    COUNT(*) AS restaurant_count

FROM restaurants

GROUP BY price_segment
order by avg_rating desc
"""
q6= pd.read_sql(query6, conn)
q6

  price_segment  avg_rating  restaurant_count
0       Premium        4.18              4738
1           Mid        3.85             11629
2           Low        3.82              6784

In [33]:
fig6 = px.bar(
    q6,
    x="price_segment",
    y="avg_rating",
    text="avg_rating",
    title="Average Rating by Price Segment",
    color="price_segment",
    color_discrete_sequence=["#F5AFAF", "#AFCBFF", "#C7F0BD"],
)

fig6.update_traces(textposition="outside")

fig6.update_layout(
    height=500,
    width=600,
    #template="plotly_white",
    margin=dict(l=50, r=30, t=50, b=30),
    
    #xaxis=dict(range=[600,1900]),
    #yaxis=dict(range=[3.5,4.3]),
   # yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    #yaxis_title="<b>Average rating</b>",
    #xaxis_title="<b>price segment </b>"
)

In [34]:
query11='''SELECT
    location,
    ROUND(AVG(rate),2) AS avg_rating,
    ROUND(AVG("approx_cost(for two people)"),2) AS avg_cost,
    COUNT(*) AS restaurants
FROM restaurants
GROUP BY location
HAVING avg_rating > 4
ORDER BY avg_cost DESC
limit 10;'''
q11= pd.read_sql(query11, conn)
q11

                location  avg_rating  avg_cost  restaurants
0            Sankey Road        4.11   2802.94           17
1           Lavelle Road        4.19   1425.80          440
2          Richmond Road        4.03   1124.79          351
3         Residency Road        4.05   1092.71          439
4                 Ulsoor        4.02   1074.58          476
5        Cunningham Road        4.10    957.08          332
6         Sadashiv Nagar        4.06    950.00           38
7  Koramangala 3rd Block        4.10    925.47          161
8         St. Marks Road        4.10    917.93          304
9          Church Street        4.05    855.54          505

In [35]:
fig11 = px.bar(
    q11,
    x="location",
    y="avg_cost",
    text="avg_cost",
    title="Best location for premium restaurant onboarding",
    color_discrete_sequence=["#dbb42c"]
)

fig11.update_traces(textposition="outside")

fig11.update_layout(
    height=500,
    width=700,
    #template="plotly_white",
    margin=dict(l=50, r=50, t=50, b=100),
    xaxis_title="",
    yaxis_title="<b>Average Cost</b>")

In [36]:
#Which locations show high demand but lower average ratings?
#Business Value: Indicates areas where quality improvement initiatives are needed.


query12 = """
SELECT
    location,
    ROUND(AVG(rate),2) AS avg_rating,
    COUNT(*) AS restaurant_count
FROM restaurants
GROUP BY location
HAVING COUNT(*) > 500
ORDER BY avg_rating ASC
"""


q12 = pd.read_sql(query12, conn)
q12

                 location  avg_rating  restaurant_count
0            Marathahalli        3.73               680
1                     BTM        3.76              1454
2              Whitefield        3.82               824
3                     HSR        3.84              1161
4                JP Nagar        3.85              1016
5            Brigade Road        3.94               567
6               Jayanagar        3.94              1037
7   Koramangala 6th Block        3.95               718
8                 MG Road        3.95               595
9             Indiranagar        3.96              1344
10  Koramangala 7th Block        3.99               723
11  Koramangala 4th Block        4.04               644
12          Church Street        4.05               505
13  Koramangala 5th Block        4.15              1782

In [37]:
fig12 = px.bar(
    q12,
    x="restaurant_count",
    y="location",
    orientation="h",
    text="restaurant_count",
    title="High Demand Locations with Lower Ratings",
    color="avg_rating",
    color_continuous_scale="Reds_r"
)

fig12.update_layout(
    yaxis=dict(autorange="reversed"),
    margin=dict(l=300, r=50, t=50, b=100),
    yaxis_title=""
)

In [38]:
#Do restaurants offering both online ordering and table booking perform better?
 #Business Value: Validates bundled feature adoption for partners.



query13 = """
SELECT
    online_order,
    book_table,
    ROUND(AVG(rate),2) AS avg_rating,
    COUNT(*) AS restaurant_count
FROM restaurants
GROUP BY online_order, book_table
ORDER BY avg_rating DESC
"""

q13 = pd.read_sql(query13, conn)
q13

  online_order book_table  avg_rating  restaurant_count
0           No        Yes        4.18              2468
1          Yes        Yes        4.15              3629
2          Yes         No        3.82             12699
3           No         No        3.79              4355

In [39]:

q13["Online_order/Book_table"] = q13["online_order"] + " / " + q13["book_table"]
fig13_avg = px.bar(
    q13,
    x="Online_order/Book_table",
    y="avg_rating",
    text="avg_rating",
    title="Average Rating by Service Combination",
    color="Online_order/Book_table",
    color_discrete_sequence=["#afab23"]
)

fig13_avg.update_traces(textposition="outside",showlegend=False)
  
fig13_avg.update_layout(
    height=500,
    width=600,
    #template="plotly_white",
    margin=dict(l=50, r=30, t=50, b=30),
    
    #xaxis=dict(range=[600,1900]),
    #yaxis=dict(range=[3.5,4.3]),
   # yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    yaxis_title="<b>Average rating</b>",
    xaxis_title="<b>Online order / Book table </b>"
)

In [40]:
q13["Online_order/Book_table"] = q13["online_order"] + " / " + q13["book_table"]
fig13_count = px.bar(
    q13,
    x="Online_order/Book_table",
    y="restaurant_count",
    text="restaurant_count",
    title=" Restaurant count by Service Combination",
    color="Online_order/Book_table",
    color_discrete_sequence=["#afab23"]
)

fig13_count.update_traces(textposition="outside",showlegend=False)
  
fig13_count.update_layout(
    height=500,
    width=600,
    #template="plotly_white",
    margin=dict(l=50, r=30, t=50, b=30),
    
    #xaxis=dict(range=[600,1900]),
    #yaxis=dict(range=[3.5,4.3]),
   # yaxis=dict(autorange="reversed"),
   # xaxis=dict(tickangle=-90),
    yaxis_title="<b>Restaurant count</b>",
    xaxis_title="<b>Online order / Book table </b>"
)

In [53]:
query15_low = """
SELECT
    name,
    location,
    ROUND(AVG(rate),2) AS rate,
    MAX(votes) AS votes,
    MAX("approx_cost(for two people)") AS cost
FROM restaurants
WHERE "approx_cost(for two people)" <= 400
GROUP BY name, location
ORDER BY rate DESC, votes DESC
LIMIT 5;
"""

q15_low = pd.read_sql(query15_low, conn)
q15_low

                     name               location  rate  votes  cost
0        Milano Ice Cream            Indiranagar  4.90   2090   400
1  Belgian Waffle Factory           Brigade Road  4.90   1750   400
2  Belgian Waffle Factory  Koramangala 5th Block  4.81    201   400
3    Brahmin's Coffee Bar           Basavanagudi  4.80   2679   100
4      O.G. Variar & Sons            Rajajinagar  4.80   1161   200

In [84]:
q15_low["restaurant_name"] = (q15_low["name"] + " (" + q15_low["location"] + ")")
fig15_low = px.bar(
    q15_low,
    x="restaurant_name",
    y="rate",
    hover_data=["votes"],
    color_discrete_sequence=["#6082B6"]
)


fig15_low.update_layout(
    height=500,
    width=700,
    yaxis=dict(range=[4.7,5]),
    #yaxis=dict(autorange="reversed"),
    margin=dict(l=50, r=130, t=50, b=160),
    yaxis_title="Rating"
)

In [42]:
query15_mid = """
SELECT
    name,
    location,
    ROUND(AVG(rate),2) AS rate,
    MAX(votes) AS votes,
    MAX("approx_cost(for two people)") AS cost
FROM restaurants
WHERE "approx_cost(for two people)" > 400
  AND "approx_cost(for two people)" <= 1000
GROUP BY name, location
ORDER BY rate DESC, votes DESC
LIMIT 5;"""
q15_mid=pd.read_sql(query15_mid,conn)
q15_mid

,name,location,rate,votes,cost
0,SantÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ...,Indiranagar,4.90,246,1000
1,House Of Commons,Koramangala 5th Block,4.73,4470,1000
2,Truffles,Koramangala 5th Block,4.70,14726,900
3,TBC Sky Lounge,HSR,4.70,6745,1000
4,Truffles,New BEL Road,4.70,3916,900

In [94]:
q15_mid["restaurant_name"] = (
    q15_mid["name"].str[:20] + "... (" + q15_mid["location"] + ")"
)
fig15_mid = px.bar(
    q15_mid,
    x="restaurant_label",
    y="rate",
    hover_data=["name", "location", "votes"],
    color_discrete_sequence=["#2E8B57"]
)


fig15_mid.update_layout(
    height=500,
    width=700,
    #s=dict(range=[4.7,5]),
    #yaxis=dict(autorange="reversed"),
    margin=dict(l=50, r=130, t=50, b=160),
    yaxis_title="Rating",
    xaxis_title=""
)

In [124]:
query15_premium = """
SELECT
    name,
    location,
    ROUND(AVG(rate),2) AS rate,
    MAX(votes) AS votes,
    MAX("approx_cost(for two people)") AS cost
FROM restaurants
WHERE "approx_cost(for two people)" > 1000
GROUP BY name, location
ORDER BY rate DESC, votes DESC
LIMIT 10;"""
q15_premium=pd.read_sql(query15_premium,conn)
q15_premium

                             name               location  rate  votes  cost
0     Byg Brewski Brewing Company          Sarjapur Road  4.90  16832  1600
1       AB's - Absolute Barbecues                    BTM  4.90   6490  1600
2                        Flechazo             Whitefield  4.90   3004  1400
3  Asia Kitchen By Mainland China  Koramangala 5th Block  4.90   2256  1500
4                    Punjab Grill           Malleshwaram  4.90   1985  2000
5                    Punjab Grill             Whitefield  4.83    654  2000
6       AB's - Absolute Barbecues           Marathahalli  4.80  12121  1600
7                 The Black Pearl           Marathahalli  4.80   7284  1500
8    Chili's American Grill & Bar           Malleshwaram  4.80   6470  1400
9               The Boozy Griffin           Marathahalli  4.80   4705  1800

In [98]:
#q15_premium["restaurant_name"] = (
#    q15_premium["name"].str[:20] + "... (" + q15_premium["location"] + ")")
fig15_premium= px.bar(
    q15_premium,
    x="name",
    y="rate",
    hover_data=["name", "location", "votes"],
    color_discrete_sequence=["#76FF7A"]
)


fig15_premium.update_layout(
    height=500,
    width=700,
    yaxis=dict(range=[4.7,5]),
    #yaxis=dict(autorange="reversed"),
    margin=dict(l=50, r=130, t=50, b=160),
    yaxis_title="Rating",
    xaxis_title=""
)

In [44]:
Order_df.head(20)

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI
5,7d1b5f22-5bfd-42fd-90d1-4040a4aa8729,Cheesiano Pizza,2025-11-05,1179.90,No,Cash
6,96475dc3-1433-4792-8998-876b3efa6c59,Fullyfilled,2025-05-30,826.06,Yes,UPI
7,a2b66255-a6f7-4dcc-9a2b-45bf36e6da55,Bawarchi Inn,2025-12-26,1318.03,Yes,UPI
8,e44b23ce-6d29-4c09-9eac-9d4f24f56fd9,Sunny Cafe & Kitchen,2025-11-13,692.33,No,Cash
9,25b2d40b-35b3-40f7-9cbe-37bf690db837,Bathinda Junction,2025-12-08,455.51,No,Card
10,28bcfd85-fd84-458c-851b-60311c625d01,Gudguda Prime Cafe,2025-11-12,937.88,No,UPI
11,11c7ea0f-cafa-4b63-a14e-7129fa934e95,The Blue Wagon - Kitchen,2025-05-11,1446.03,Yes,UPI
12,00a0c73e-b797-4322-afc4-6199d5f68ce9,Shaan-E-Punjab,2025-09-23,1442.41,No,UPI
13,98ccc839-fea8-4d92-9ba0-5a1ab4b8bff8,Oottupura,2025-07-25,1019.59,No,Cash
14,a7fc803c-b863-461a-b18d-e713d525485c,Mangalore Pearl,2025-09-21,459.17,No,Cash
15,659aa47b-9044-4e2a-b49e-7c7f1dfbea09,Carnatic,2025-10-30,407.38,Yes,Card
16,baa7fac2-c7f7-4405-abe2-6f2a3beb4b78,Biryani Mane,2025-12-31,855.87,Yes,Card
17,57ce4802-690a-4ea3-8656-ac73758cff36,Eatapita,2025-12-25,1097.72,No,Card
18,bd9e4f83-e1f6-4db6-a6c8-e2d6bea58408,Al Khansah,2025-08-20,862.20,Yes,UPI
19,f960b9ca-2b36-4a02-9a07-85d7ecda1254,Bon Appetit Resto,2025-09-14,434.60,No,UPI

In [45]:
Order_df.tail(20)

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
24980,4519d493-de90-46a2-8715-46558c78b4cc,Pabrai's Fresh and Naturelle Icecreams,2025-05-11,1105.72,No,Cash
24981,0869a77f-746a-40ef-ac5d-18f2d353671c,Tiffun,2025-09-01,1541.19,Yes,Cash
24982,7f1d560f-0ef7-4cfe-987b-40c6dde3e5f8,Vitamin Palace,2025-06-29,325.14,No,Card
24983,2ee61aee-450f-4826-8aec-e8dd891e27ab,Foodishq,2026-01-30,1142.84,No,Cash
24984,e9fc0da3-373f-4351-b21f-e25c98a5be2a,Coastal Inn,2025-07-31,555.70,Yes,Cash
24985,297f5220-8ffb-4e3c-85ef-e35f11446df1,The Daily,2026-02-02,490.77,No,Card
24986,3996c9e0-f3b2-42da-ae99-278862ef5cc1,Coastal Inn,2025-06-10,843.11,No,Cash
24987,a8787d3d-f2e6-43d3-b7ac-5c3a09d81c28,Saara's Cafe - SS Lumina Hotel,2025-07-21,1001.93,No,UPI
24988,eb497616-0d4d-487c-9dfe-57952a84787c,SlimSins Cafe,2025-08-05,535.90,Yes,UPI
24989,cab57565-cd0e-4999-8da7-e68bb5527709,eat.fit,2025-08-14,740.28,No,Cash
24990,bc7f3f02-bf4e-4eb8-8889-84ac9f88c029,UTHRA,2025-10-22,1262.55,No,Card
24991,efd64b7f-621c-432a-a09e-b26860a5230b,ThrowBack - Pub & Dine,2025-09-26,1196.51,Yes,UPI
24992,121a1946-9e4b-4868-a146-32c4524c89fd,The Rolling Pin,2026-02-19,1847.63,Yes,Cash
24993,fe12a139-f2fd-498a-9395-27666eaa7089,Adukkala Restaurant,2025-09-27,1405.24,Yes,Cash
24994,a66b19d3-7232-41a4-a015-08af55c56f17,Lotus Pavilion - ITC Gardenia,2026-01-01,978.77,Yes,Card
24995,74d3cd31-c1e0-4331-aad7-e1f48b4698ae,Carnatic,2025-11-24,1254.91,No,UPI
24996,14db2f6b-f722-44a2-ae55-fe42511e4bb2,Reddy's Restaurant,2025-06-24,760.39,No,Card
24997,0fd85321-c1ce-4163-beca-c8ed2b472b8d,BTM Bawarchi Biryani,2025-12-04,707.99,Yes,Card
24998,6b96c699-2d63-4a3c-84f1-5d52ca4bf357,Nite Out,2025-09-21,724.29,Yes,Card
24999,af55e28b-27fc-49fc-bdb0-b297999dd152,Zee5 Loft,2025-08-07,905.00,No,UPI

In [46]:
Order_df.head()

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201.87,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392.27,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358.35,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782.37,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551.09,Yes,UPI

What is the most commonly used payment method?
Which restaurant receives the highest number of orders?
Which restaurant generates the highest revenue?
Which date recorded the highest number of orders?
Which restaurant is the lowest-performing based on order volume?

In [47]:
#Most used payment method
Order_query1="""
select payment_method,count(*) as total_count
from Order_details
group by payment_method	
order by total_count"""
Order_q1=pd.read_sql(Order_query1,conn)
Order_q1

  payment_method  total_count
0            UPI         8252
1           Card         8364
2           Cash         8384

In [ ]:
fig_o1= px.pie(
    Order_q1,
    names="payment_method",
    values="total_count",
    title="Payment Method Distribution",
    color_discrete_sequence=["#DAA06D","#954535","#AF6E4D"]
)
fig_o1.update_traces(
    textposition="inside",
    textinfo="percent+label"
)
fig_o1

In [ ]:
#Highest order volume restaurant
Order_query2="""
select restaurant_name,count(*) as total_count
from Order_details
group by restaurant_name
order by total_count desc
Limit 10"""
Order_q2=pd.read_sql(Order_query2,conn)
Order_q2

                      restaurant_name  total_count
0                           Cake Cafe           19
1                       Andhra Grills           19
2                Shree Muthahalli Veg           18
3                  Reddy's Restaurant           18
4                    Orbis Restaurant           18
5                          Hungry Lee           18
6                         Mighty Paws           17
7                                Melt           17
8  JW Kitchen - JW Marriott Bengaluru           17
9                              Aubree           17

In [111]:
fig_o2 = px.bar(
    Order_q2,
    x="total_count",
    y="restaurant_name",
    orientation="h",
    text="total_count",
    title="Top 10 Restaurants by Order Volume",
    color_discrete_sequence=["#905D5D"]
)

fig_o2.update_traces(textposition="outside")

fig_o2.update_layout(
    height=500,
    width=800,
    margin=dict(l=200, r=30, t=50, b=30),
    yaxis=dict(autorange="reversed"),
    xaxis_title="<b>Total Orders</b>",
    yaxis_title=""
)

In [49]:
Order_q2[Order_q2.duplicated(keep=False)]

Empty DataFrame
Columns: [restaurant_name, total_count]
Index: []

In [50]:
#Highest revenue restaurant
Order_query3="""
select restaurant_name,sum(order_value) as total_revenue
from Order_details
group by restaurant_name
order by total_revenue desc
Limit 10"""
Order_q3=pd.read_sql(Order_query3,conn)
Order_q3

       restaurant_name  total_revenue
0            Bob's Bar       19518.14
1            Cake Cafe       19335.17
2         Biryani Mane       19249.45
3           Hungry Lee       19167.53
4        Andhra Grills       19153.72
5          Mighty Paws       18410.50
6    Delhi Ke Bawarchi       18131.68
7              Pingara       17954.06
8         Bawarchi Inn       17717.43
9  Soup'ermanz Kitchen       17350.72

In [120]:
fig_o3 = px.bar(
    Order_q3,
    x="total_revenue",
    y="restaurant_name",
    orientation="h",
    text="total_revenue",
    title="Top 10 Restaurants by Revenue",
    color="total_revenue",
    color_continuous_scale="Greens"
)

fig_o3.update_traces(textposition="outside")

fig_o3.update_layout(
    height=500,
    width=800,
    xaxis=dict(range=[16000,20000]),
    margin=dict(l=140, r=30, t=50, b=30),
    yaxis=dict(autorange="reversed"),
    xaxis_title="<b>Total Revenue</b>",
    yaxis_title=""
)
fig_o3.update_traces(
    texttemplate="₹%{x:,.0f}",
    textposition="outside"
)

In [51]:
#Highest order day/date
Order_query4 = """
SELECT
    CASE strftime('%w', order_date)
        WHEN '0' THEN 'Sunday'
        WHEN '1' THEN 'Monday'
        WHEN '2' THEN 'Tuesday'
        WHEN '3' THEN 'Wednesday'
        WHEN '4' THEN 'Thursday'
        WHEN '5' THEN 'Friday'
        WHEN '6' THEN 'Saturday'
    END AS day_name,
    COUNT(*) AS total_count
FROM Order_details
GROUP BY day_name
ORDER BY total_count DESC
"""
Order_q4 = pd.read_sql(Order_query4, conn)
Order_q4

    day_name  total_count
0   Thursday         3623
1     Monday         3613
2  Wednesday         3598
3    Tuesday         3596
4     Friday         3567
5   Saturday         3505
6     Sunday         3498

In [123]:
day_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

Order_q4["day_name"] = pd.Categorical(
    Order_q4["day_name"],
    categories=day_order,
    ordered=True
)

Order_q4 = Order_q4.sort_values("day_name")
fig_o4 = px.line(
    Order_q4,
    x="day_name",
    y="total_count",
    markers=True,
    title="Orders by Day of Week"
)
fig_o4

In [52]:
#Which day of the week generates the highest revenue?
Order_query5 = """
SELECT
    CASE strftime('%w', order_date)
        WHEN '0' THEN 'Sunday'
        WHEN '1' THEN 'Monday'
        WHEN '2' THEN 'Tuesday'
        WHEN '3' THEN 'Wednesday'
        WHEN '4' THEN 'Thursday'
        WHEN '5' THEN 'Friday'
        WHEN '6' THEN 'Saturday'
    END AS day_name,sum(order_value) as total_value
    
FROM Order_details
GROUP BY day_name
ORDER BY total_value DESC
"""
Order_q5 = pd.read_sql(Order_query5, conn)
Order_q5

    day_name  total_value
0     Monday   3601117.87
1    Tuesday   3547281.47
2     Friday   3539518.75
3  Wednesday   3517348.48
4   Thursday   3509006.41
5   Saturday   3494384.74
6     Sunday   3443389.10